# Generated by Django 2.2.6 on 2019-10-13 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='titile',
            new_name='title',
        ),
    ]
